### Evolution of PyTorch

#### Early features
- **Dynamic computation graph** → graph can change at run time
    - more flexibility
    - easier experimentation
- **TorchScript** → model serialization + optimization
- **Merger with Caffe2**

#### In subsequent versions
- **Distributed training**
- **ONNX compatibility** → other libraries can also use a model saved in ONNX format
- **Quantization** introduced → model compression + efficiency
- **Expanded ecosystem** → `torchvision`, `torchaudio`, `torchtext`

### Core features
- **Tensor computations**
- **GPU acceleration**
- **Dynamic computation graph**
- **Automatic differentiation**
- **Distributed training**
- **Interoperability** with other libraries

### Tensors

A **tensor** is basically a data structure → a generalization of multi-dimensional arrays, used for mathematical operations and computational efficiency.

**Dimension** → how many directions a tensor spans (i.e., its number of axes)

| Dim | Example |
|---|---|
| 0-D | Scalar |
| 1-D | Vectors, word embeddings |
| 2-D | Grayscale image |
| 3-D | RGB image |
| 4-D | Batches of RGB images |
| 5-D | Batch of video clips (see below) |

**5-D example** → batch of 10 video clips, each with 16 frames of size 64×64 and 3 channels
- shape: `[10, 16, 64, 64, 3]`
- read as: `[batch, frames, height, width, channels]`

#### Why are tensors so useful?
1. **Very efficient** at operations like addition, multiplication and dot product → all necessary for NN operations
2. **Real-world data** can be represented easily using tensors
3. Can run on **GPUs** and **parallelize** them too

#### Where are tensors used in DL?
1. **Data storage** → training / testing data
2. **Storing weights and biases**
3. **Matrix operations** → multiplication, dot product, broadcasting
4. **Forward pass and backward pass** (gradients)

In [97]:
import torch

print(torch.__version__)

2.14.0


In [98]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}") 
else:
    print("GPU is not available")

GPU is not available


In [99]:
if torch.backends.mps.is_available() and torch.backends.mps.is_built():
    print("MPS is available")
else:
    print("MPS is not available")


MPS is available


In [100]:
mps_device = torch.device("mps")

## Creating a Tensor

In [101]:
# creates a tensor without initializing it's values
# allocates memory but doesn't spend time filling it with values

a = torch.empty(2, 3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [102]:
type(a)

torch.Tensor

In [103]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [104]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [105]:
# random values
torch.rand(2, 3)

tensor([[0.3833, 0.5534, 0.7082],
        [0.7997, 0.4324, 0.3699]])

In [106]:
# defining seed for reproducibility
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [107]:
# custom tensor
# we can provide any python iterable
torch.tensor([[2, 3, 4], [4, 5, 6]])

tensor([[2, 3, 4],
        [4, 5, 6]])

In [108]:
torch.arange(0, 10, 2) # step = 1 by default

tensor([0, 2, 4, 6, 8])

In [109]:
# evenly spaced values
torch.linspace(0, 10, 4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [110]:
# identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [111]:
torch.full((3, 4), -2)

tensor([[-2, -2, -2, -2],
        [-2, -2, -2, -2],
        [-2, -2, -2, -2]])

## Tensor shapes

In [112]:
x = torch.tensor([[1, 3, 5], [3, 4, 5]])
x.shape

torch.Size([2, 3])

In [113]:
# same shape, values different
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [114]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [115]:
torch.rand_like(x.to(torch.float32))
torch.rand_like(x, dtype=torch.float32)
# torch.rand_like(x) - error

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor Data Types

In [116]:
x.dtype

torch.int64

In [117]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [118]:
torch.tensor([[4, 5], [3, 7]], dtype=torch.float64)

tensor([[4., 5.],
        [3., 7.]], dtype=torch.float64)

In [119]:
x.dtype

torch.int64

In [120]:
x.to(torch.float32)
x.dtype

torch.int64

## Mathematical operations

In [121]:
x = torch.rand((3, 1))
print(x)

tensor([[0.2239],
        [0.3023],
        [0.1784]])


### Scalar operations

In [122]:
x + 2
x - 2
x * 2
x / 2
x // 2
x % 2
x ** 2

tensor([[0.0501],
        [0.0914],
        [0.0318]])

### Element wise operations

In [123]:
a = torch.rand(2, 4)
b = torch.rand(2, 4)

print(a)
print(b)

tensor([[0.8238, 0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892, 0.2426]])
tensor([[0.7003, 0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209, 0.9535]])


In [124]:
a + b
a - b
a * b
a / b
a // b
a ** b
a % b

tensor([[0.1235, 0.0281, 0.2355, 0.4440],
        [0.1009, 0.0009, 0.0474, 0.2426]])

In [125]:
c = torch.tensor([3, -1, 4.4])
print(c.dtype)

# abs 
print(torch.abs(c))

# negative
print(torch.negative(c))

# round
print(torch.round(c))

# ceil
print(torch.ceil(c))

# floor 
print(torch.floor(c))

# clamp
print(torch.clamp(c, min=1, max=4))



torch.float32
tensor([3.0000, 1.0000, 4.4000])
tensor([-3.0000,  1.0000, -4.4000])
tensor([ 3., -1.,  4.])
tensor([ 3., -1.,  5.])
tensor([ 3., -1.,  4.])
tensor([3., 1., 4.])


### Reduction operations

In [126]:
d = torch.randint(size=(2, 3), low=2, high=5)
print(d)

tensor([[2, 4, 4],
        [2, 4, 2]])


In [127]:
print(torch.sum(d))
print(torch.sum(d, dim=1))
print(torch.sum(d, dim=0))

tensor(18)
tensor([10,  8])
tensor([4, 8, 6])


In [128]:
print(torch.mean(d.to(torch.float32)))
print(torch.mean(d.to(torch.float32), dim=1))

tensor(3.)
tensor([3.3333, 2.6667])


In [129]:
torch.median(d)

tensor(2)

In [130]:
print(torch.max(d))
print(torch.min(d))

tensor(4)
tensor(2)


In [131]:
torch.prod(d)

tensor(512)

In [132]:
print(torch.std(d.to(torch.float32)))
print(torch.var(d.to(torch.float32)))

tensor(1.0954)
tensor(1.2000)


In [133]:
print(torch.argmax(d))
print(torch.argmin(d))

tensor(1)
tensor(0)


## Matrix operations

In [134]:
e = torch.randint(size=(2,3), low=0, high=10)
f = torch.randint(size=(2,3), low=0, high=10)

In [135]:
# matrix multiplication
torch.matmul(e, f.T)

tensor([[207, 121],
        [180, 120]])

In [136]:
g = torch.tensor([2, 4, 5, 6])
h = torch.tensor([4, 6, 3, 6])

# dot product
torch.dot(g, h)

tensor(83)

In [137]:
i = torch.randint(size=(2, 3, 4), low=0, high=10)
print(i)

# transpose
print(torch.transpose(i, 0, 1))
print(torch.transpose(i, 1, 2))

tensor([[[7, 8, 3, 6],
         [1, 5, 5, 0],
         [4, 3, 8, 8]],

        [[3, 3, 5, 0],
         [6, 4, 0, 8],
         [4, 7, 2, 3]]])
tensor([[[7, 8, 3, 6],
         [3, 3, 5, 0]],

        [[1, 5, 5, 0],
         [6, 4, 0, 8]],

        [[4, 3, 8, 8],
         [4, 7, 2, 3]]])
tensor([[[7, 1, 4],
         [8, 5, 3],
         [3, 5, 8],
         [6, 0, 8]],

        [[3, 6, 4],
         [3, 4, 7],
         [5, 0, 2],
         [0, 8, 3]]])


In [138]:
# determinant 

j = torch.rand((3, 3))
print(torch.det(j))
print(torch.inverse(j))

tensor(-0.0360)
tensor([[ 5.8755, -4.2960, -1.7014],
        [ 0.7568, -4.8693,  4.2739],
        [-2.0277,  2.5800,  0.5387]])


## Comparison operations

In [139]:
k = torch.rand(2, 3)
l = torch.rand(2, 3)

print(k == l)
print(k < l)
print(k > l)
print(k != l)
print(k >= l)
print(k <= l)

tensor([[False, False, False],
        [False, False, False]])
tensor([[False,  True, False],
        [ True, False,  True]])
tensor([[ True, False,  True],
        [False,  True, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[ True, False,  True],
        [False,  True, False]])
tensor([[False,  True, False],
        [ True, False,  True]])


## Special functions

In [140]:
m = torch.randint(size=(2,3), low=1, high=10, dtype=torch.float32)

In [141]:
torch.log(m)

tensor([[1.9459, 0.6931, 0.0000],
        [1.9459, 1.3863, 0.0000]])

In [142]:
torch.sqrt(m)

tensor([[2.6458, 1.4142, 1.0000],
        [2.6458, 2.0000, 1.0000]])

In [143]:
torch.exp(m)

tensor([[1096.6332,    7.3891,    2.7183],
        [1096.6332,   54.5982,    2.7183]])

In [144]:
torch.sigmoid(m)

tensor([[0.9991, 0.8808, 0.7311],
        [0.9991, 0.9820, 0.7311]])

In [145]:
torch.softmax(m, dim=1)

tensor([[0.9909, 0.0067, 0.0025],
        [0.9503, 0.0473, 0.0024]])

In [146]:
torch.relu(m)

tensor([[7., 2., 1.],
        [7., 4., 1.]])

## Inplace operations

In [147]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])


In [148]:
m + n    # completely new tensor in memory

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [149]:
# inplace

m.add_(n) # changes made and stored in m

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [150]:
m.relu_()

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

## Compying a tensor

In [151]:
a = torch.rand(2, 3)

In [152]:
b = a  # not a copy, rather a reference pointing to a

a[0][0] = 0
print(a)
print(b)

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])
tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])


In [153]:
# both are pointing to the same memory location
print(id(a))
print(id(b))

4972102032
4972102032


In [154]:
b = a.clone()

a.exp_()
print(a)
print(b)

tensor([[1.0000, 1.2839, 1.3780],
        [2.6519, 2.1344, 1.9519]])


tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])


In [155]:
print(id(a))
print(id(b))

4972102032
5053967376


## Tensor operations on GPU

In [156]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}") 
else:
    print("GPU is not available")

GPU is not available


In [157]:
if torch.backends.mps.is_available() and torch.backends.mps.is_built():
    print("MPS is available")
else:
    print("MPS is not available")

MPS is available


In [158]:
device = torch.device("mps")

In [159]:
# creating a new tensor on MPS

torch.rand((2, 3), device=device)

tensor([[0.2580, 0.0222, 0.3388],
        [0.4191, 0.2168, 0.9068]], device='mps:0')

In [160]:
# more existing tensor to MPS

a = torch.rand(2, 3)
b = a.to(device)

print(a)
print(b)

tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])
tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]], device='mps:0')


In [161]:
# time comparison

import time

a = torch.rand((5000, 4000))
b = torch.rand((5000, 4000))

start_time = time.time()
res_cpu = torch.matmul(a, b.T) 
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time}")

c = a.to(device)
d = b.to(device)

torch.mps.synchronize()
start_time = time.time()

res_cpu = torch.matmul(c, d.T) 

torch.mps.synchronize()
mps_time = time.time() - start_time

print(f"Time on MPS: {mps_time}")

Time on CPU: 0.2822561264038086
Time on MPS: 0.2400503158569336


## Reshaping tensors

In [162]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [163]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [164]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [165]:
b = torch.rand(2,3,4)
b.shape

torch.Size([2, 3, 4])

In [166]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [167]:
# unsqueeze - adds a dimension at a given position

c = torch.randint(size=(226,226,3), low=0, high=255)
print(c.shape)

c.unsqueeze(0).shape # example: converting a single image into a batch of 1 image

torch.Size([226, 226, 3])


torch.Size([1, 226, 226, 3])

In [168]:
d = torch.rand(1,20)
print(d.shape)

print(d.squeeze(0).shape)

torch.Size([1, 20])
torch.Size([20])


## NumPy and PyTorch

In [169]:
import numpy as np

In [170]:
a = torch.tensor([2, 3, 4])
a

tensor([2, 3, 4])

In [171]:
b = a.numpy()
b

array([2, 3, 4])

In [172]:
c = np.array([3, 4, 5])
c

array([3, 4, 5])

In [173]:
d = torch.from_numpy(c)
d

tensor([3, 4, 5])